[[pages]]
path = "overview.py"
name = "Overview"
icon = "ğŸ¡"

[[pages]]
path = "model_validation.py"
name = "Model Validation"
icon = "âœ…"

[[pages]]
path = "forecast_cpi.py"
name = "Short-Term CPI Forecasting"
icon = "ğŸ“Š"

[[pages]]
path = "forecast_cpi_l.py"
name = "Long-Term CPI Forecasting"
icon = "ğŸš€"

[[pages]]
path = "cpi_percent_change.py"
name = "Monthly CPI Trends"
icon = "ğŸ“ˆ"

[[pages]]
path = "cpi_percent_change_y.py"
name = "Yearly CPI Trends"
icon = "ğŸ“‰"

[[pages]]
path = "contact.py"
name = "Contact Us"
icon = "ğŸ“©"


[theme]
base="light"
primaryColor="#C982EF"
textColor="#3b3b3b"
font = "sans serif"